"""Create a score table and link it to user table

Revision ID: 111a432ca7fa
Revises: d1e4a491e2ae
Create Date: 2024-12-08 23:05:00.598208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "111a432ca7fa"
down_revision: Union[str, None] = "d1e4a491e2ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("temps", sa.Integer(), nullable=False),
        sa.Column("tentative", sa.Integer(), nullable=False),
        sa.Column("Score", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score")
    # ### end Alembic commands ###
